export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export GOPATH="$XDG_CONFIG_HOME/go"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/Users/cheng/.gem/ruby/2.6.0/bin:$PATH"
